/**
 * Configuration for GOES/Suomi NPP Data Downloader
 * Includes ALL available products from NOAA S3 buckets
 */

const ABI_BANDS = ['C01','C02','C03','C04','C05','C06','C07','C08','C09','C10','C11','C12','C13','C14','C15','C16'];

const CONFIG = {
  satellites: {
    'GOES-16': {
      bucket: 'noaa-goes16',
      products: {
        'ABI-L1b-RadC': { name: 'ABI L1b Radiance (CONUS)', bands: ABI_BANDS },
        'ABI-L1b-RadF': { name: 'ABI L1b Radiance (Full Disk)', bands: ABI_BANDS },
        'ABI-L1b-RadM': { name: 'ABI L1b Radiance (Mesoscale)', bands: ABI_BANDS },
        'ABI-L2-CMIPC': { name: 'ABI L2 CMIP (CONUS)', bands: ABI_BANDS },
        'ABI-L2-CMIPF': { name: 'ABI L2 CMIP (Full Disk)', bands: ABI_BANDS },
        'ABI-L2-CMIPM': { name: 'ABI L2 CMIP (Mesoscale)', bands: ABI_BANDS },
        'ABI-L2-LSTC': { name: 'ABI L2 LST (CONUS)', bands: ABI_BANDS },
        'ABI-L2-LSTF': { name: 'ABI L2 LST (Full Disk)', bands: ABI_BANDS },
        'ABI-L2-LSTM': { name: 'ABI L2 LST (Mesoscale)', bands: ABI_BANDS },
        'ABI-L2-TPWC': { name: 'ABI L2 TPW (CONUS)', bands: ABI_BANDS },
        'ABI-L2-TPWF': { name: 'ABI L2 TPW (Full Disk)', bands: ABI_BANDS },
        'ABI-L2-TPWM': { name: 'ABI L2 TPW (Mesoscale)', bands: ABI_BANDS },
        'GLM-L2-LCFA': { name: 'GLM L2 LCFA', bands: null },
        'EXIS-L1b-SFEU': { name: 'EXIS L1b SFEU', bands: null },
        'EXIS-L1b-SFXR': { name: 'EXIS L1b SFXR', bands: null },
        'MAG-L1b-GEOF': { name: 'MAG L1b GEOF', bands: null },
        'SEIS-L1b-EHIS': { name: 'SEIS L1b EHIS', bands: null },
        'SEIS-L1b-MPSH': { name: 'SEIS L1b MPSH', bands: null },
        'SEIS-L1b-MPSL': { name: 'SEIS L1b MPSL', bands: null },
        'SEIS-L1b-SGPS': { name: 'SEIS L1b SGPS', bands: null },
        'SUVI-L1b-Fe093': { name: 'SUVI L1b Fe093', bands: null },
        'SUVI-L1b-Fe131': { name: 'SUVI L1b Fe131', bands: null },
        'SUVI-L1b-Fe171': { name: 'SUVI L1b Fe171', bands: null },
        'SUVI-L1b-Fe195': { name: 'SUVI L1b Fe195', bands: null },
        'SUVI-L1b-Fe284': { name: 'SUVI L1b Fe284', bands: null },
        'SUVI-L1b-He303': { name: 'SUVI L1b He303', bands: null }
      }
    satellites: {
      'NOAA-20': {
        bucket: 'noaa-nesdis-n20-pds',
        products: {
          ...existing code...
        }
      },
      'NOAA-21': {
        bucket: 'noaa-nesdis-n21-pds',
        products: {
          ...existing code...
        }
      }
    },
        'ABI-L2-TPWC': { name: 'ABI L2 TPW (CONUS)', bands: ABI_BANDS },
        'ABI-L2-TPWF': { name: 'ABI L2 TPW (Full Disk)', bands: ABI_BANDS },
        'ABI-L2-TPWM': { name: 'ABI L2 TPW (Mesoscale)', bands: ABI_BANDS },
        'GLM-L2-LCFA': { name: 'GLM L2 LCFA', bands: null },
        'EXIS-L1b-SFEU': { name: 'EXIS L1b SFEU', bands: null },
        'EXIS-L1b-SFXR': { name: 'EXIS L1b SFXR', bands: null },
        'MAG-L1b-GEOF': { name: 'MAG L1b GEOF', bands: null },
        'SEIS-L1b-EHIS': { name: 'SEIS L1b EHIS', bands: null },
        'SEIS-L1b-MPSH': { name: 'SEIS L1b MPSH', bands: null },
        'SEIS-L1b-MPSL': { name: 'SEIS L1b MPSL', bands: null },
        'SEIS-L1b-SGPS': { name: 'SEIS L1b SGPS', bands: null },
        'SUVI-L1b-Fe093': { name: 'SUVI L1b Fe093', bands: null },
        'SUVI-L1b-Fe131': { name: 'SUVI L1b Fe131', bands: null },
        'SUVI-L1b-Fe171': { name: 'SUVI L1b Fe171', bands: null },
        'SUVI-L1b-Fe195': { name: 'SUVI L1b Fe195', bands: null },
        'SUVI-L1b-Fe284': { name: 'SUVI L1b Fe284', bands: null },
        'SUVI-L1b-He303': { name: 'SUVI L1b He303', bands: null }
      }
    },
    'GOES-19': {
      bucket: 'noaa-goes19',
      products: {
        'ABI-L1b-RadC': { name: 'ABI L1b Radiance (CONUS)', bands: ABI_BANDS },
        'ABI-L1b-RadF': { name: 'ABI L1b Radiance (Full Disk)', bands: ABI_BANDS },
        'ABI-L1b-RadM': { name: 'ABI L1b Radiance (Mesoscale)', bands: ABI_BANDS },
        'ABI-L2-CMIPC': { name: 'ABI L2 CMIP (CONUS)', bands: ABI_BANDS },
        'ABI-L2-CMIPF': { name: 'ABI L2 CMIP (Full Disk)', bands: ABI_BANDS },
        'ABI-L2-CMIPM': { name: 'ABI L2 CMIP (Mesoscale)', bands: ABI_BANDS },
        'ABI-L2-LSTC': { name: 'ABI L2 LST (CONUS)', bands: ABI_BANDS },
        'ABI-L2-LSTF': { name: 'ABI L2 LST (Full Disk)', bands: ABI_BANDS },
        'ABI-L2-LSTM': { name: 'ABI L2 LST (Mesoscale)', bands: ABI_BANDS },
        'ABI-L2-TPWC': { name: 'ABI L2 TPW (CONUS)', bands: ABI_BANDS },
        'ABI-L2-TPWF': { name: 'ABI L2 TPW (Full Disk)', bands: ABI_BANDS },
        'ABI-L2-TPWM': { name: 'ABI L2 TPW (Mesoscale)', bands: ABI_BANDS },
        'GLM-L2-LCFA': { name: 'GLM L2 LCFA', bands: null },
        'EXIS-L1b-SFEU': { name: 'EXIS L1b SFEU', bands: null },
        'EXIS-L1b-SFXR': { name: 'EXIS L1b SFXR', bands: null },
        'MAG-L1b-GEOF': { name: 'MAG L1b GEOF', bands: null },
        'SEIS-L1b-EHIS': { name: 'SEIS L1b EHIS', bands: null },
        'SEIS-L1b-MPSH': { name: 'SEIS L1b MPSH', bands: null },
        'SEIS-L1b-MPSL': { name: 'SEIS L1b MPSL', bands: null },
        'SEIS-L1b-SGPS': { name: 'SEIS L1b SGPS', bands: null },
        'SUVI-L1b-Fe093': { name: 'SUVI L1b Fe093', bands: null },
        'SUVI-L1b-Fe131': { name: 'SUVI L1b Fe131', bands: null },
        'SUVI-L1b-Fe171': { name: 'SUVI L1b Fe171', bands: null },
        'SUVI-L1b-Fe195': { name: 'SUVI L1b Fe195', bands: null },
        'SUVI-L1b-Fe284': { name: 'SUVI L1b Fe284', bands: null },
        'SUVI-L1b-He303': { name: 'SUVI L1b He303', bands: null }
      }
    },
    'Suomi NPP': {
      bucket: 'noaa-snpp',
      products: {
        'VIIRS-L1': { name: 'VIIRS L1', bands: ['I1', 'I2', 'I3', 'I4', 'I5', 'M1', 'M2', 'M3', 'M4', 'M5', 'M6', 'M7', 'M8', 'M9', 'M10', 'M11', 'M12', 'M13', 'M14', 'M15', 'M16'] },
        'CrIS-L1b-QL': { name: 'CrIS L1b Quality', bands: null },
        'OMPS-L2-SO2': { name: 'OMPS L2 SO2', bands: null },
        'ATMS-L1b': { name: 'ATMS L1b', bands: null }
      }
    },
    'NOAA-20': {
      bucket: 'noaa-nesdis-n20-pds',
      products: {
        'ATMS-SCIENCE-RDR': { name: 'ATMS Science RDR', bands: null },
        'ATMS-SDR-GEO': { name: 'ATMS SDR GEO', bands: null },
        'ATMS-SDR': { name: 'ATMS SDR', bands: null },
        'ATMS-SFR': { name: 'ATMS SFR', bands: null },
        'ATMS-TDR': { name: 'ATMS TDR', bands: null },
        'ATMS_BUFR': { name: 'ATMS BUFR', bands: null },
        'CRIS-SCIENCE-RDR': { name: 'CRIS Science RDR', bands: null },
        'CrIS-FS-SDR': { name: 'CrIS FS SDR', bands: null },
        'CrIS-SDR-GEO': { name: 'CrIS SDR GEO', bands: null },
        'GRIDDED_VIIRS_LSA_DLY': { name: 'Gridded VIIRS LSA Daily', bands: null },
        'GRIDDED_VIIRS_LST_D': { name: 'Gridded VIIRS LST Day', bands: null },
        'GRIDDED_VIIRS_LST_N': { name: 'Gridded VIIRS LST Night', bands: null },
        'GVF_GLB': { name: 'GVF Global', bands: null },
        'GVF_REG': { name: 'GVF Regional', bands: null },
        'JPSSRR_LST': { name: 'JPSSRR LST', bands: null },
        'JPSSRR_SnowCover': { name: 'JPSSRR Snow Cover', bands: null },
        'JPSSRR_SurfAlb': { name: 'JPSSRR Surface Albedo', bands: null },
        'L2VR2YCW': { name: 'L2VR2YCW', bands: null },
        'NPR_MIRS_IMG': { name: 'NPR MIRS IMG', bands: null },
        'NPR_MIRS_IMG_33min': { name: 'NPR MIRS IMG 33min', bands: null },
        'NPR_MIRS_SND': { name: 'NPR MIRS SND', bands: null },
        'NPR_MIRS_SND_33min': { name: 'NPR MIRS SND 33min', bands: null },
        'NUCAPS-EDR': { name: 'NUCAPS EDR', bands: null },
        'NUCAPS_C0431_BUFR': { name: 'NUCAPS C0431 BUFR', bands: null },
        'NUCAPS_C2211_BUFR': { name: 'NUCAPS C2211 BUFR', bands: null },
        'OMPS-NP-GEO': { name: 'OMPS NP GEO', bands: null },
        'OMPS-NP-SDR': { name: 'OMPS NP SDR', bands: null },
        'OMPS-TC-GEO': { name: 'OMPS TC GEO', bands: null },
        'OMPS-TC-SDR': { name: 'OMPS TC SDR', bands: null },
        'OMPS_V8TOZ': { name: 'OMPS V8TOZ', bands: null },
        'SFR_ATMS': { name: 'SFR ATMS', bands: null },
        'TLE-AUX': { name: 'TLE AUX', bands: null },
        'VIIRS-DNB-GEO': { name: 'VIIRS DNB GEO', bands: null },
        'VIIRS-DNB-SDR': { name: 'VIIRS DNB SDR', bands: null },
        'VIIRS-I1-IMG-EDR': { name: 'VIIRS I1 IMG EDR', bands: null },
        'VIIRS-I1-SDR': { name: 'VIIRS I1 SDR', bands: null },
        'VIIRS-I2-IMG-EDR': { name: 'VIIRS I2 IMG EDR', bands: null },
        'VIIRS-I2-SDR': { name: 'VIIRS I2 SDR', bands: null },
        'VIIRS-I3-IMG-EDR': { name: 'VIIRS I3 IMG EDR', bands: null },
        'VIIRS-I3-SDR': { name: 'VIIRS I3 SDR', bands: null },
        'VIIRS-I4-IMG-EDR': { name: 'VIIRS I4 IMG EDR', bands: null },
        'VIIRS-I4-SDR': { name: 'VIIRS I4 SDR', bands: null },
        'VIIRS-I5-IMG-EDR': { name: 'VIIRS I5 IMG EDR', bands: null },
        'VIIRS-I5-SDR': { name: 'VIIRS I5 SDR', bands: null },
        'VIIRS-IMG-GEO-TC': { name: 'VIIRS IMG GEO TC', bands: null },
        'VIIRS-IMG-GEO': { name: 'VIIRS IMG GEO', bands: null },
        'VIIRS-IMG-GTM-EDR-GEO': { name: 'VIIRS IMG GTM EDR GEO', bands: null },
        'VIIRS-JRR-ADP': { name: 'VIIRS JRR ADP', bands: null },
        'VIIRS-JRR-AOD': { name: 'VIIRS JRR AOD', bands: null },
        'VIIRS-JRR-CloudBase': { name: 'VIIRS JRR Cloud Base', bands: null },
        'VIIRS-JRR-CloudCoverLayers': { name: 'VIIRS JRR Cloud Cover Layers', bands: null },
        'VIIRS-JRR-CloudDCOMP': { name: 'VIIRS JRR Cloud DCOMP', bands: null },
        'VIIRS-JRR-CloudHeight': { name: 'VIIRS JRR Cloud Height', bands: null },
        'VIIRS-JRR-CloudMask': { name: 'VIIRS JRR Cloud Mask', bands: null },
        'VIIRS-JRR-CloudNCOMP': { name: 'VIIRS JRR Cloud NCOMP', bands: null },
        'VIIRS-JRR-CloudPhase': { name: 'VIIRS JRR Cloud Phase', bands: null },
        'VIIRS-JRR-IceAge': { name: 'VIIRS JRR Ice Age', bands: null },
        'VIIRS-JRR-IceConcentration': { name: 'VIIRS JRR Ice Concentration', bands: null },
        'VIIRS-JRR-VolcanicAsh': { name: 'VIIRS JRR Volcanic Ash', bands: null },
        'VIIRS-M1-SDR': { name: 'VIIRS M1 SDR', bands: null },
        'VIIRS-M10-SDR': { name: 'VIIRS M10 SDR', bands: null },
        'VIIRS-M11-SDR': { name: 'VIIRS M11 SDR', bands: null },
        'VIIRS-M12-SDR': { name: 'VIIRS M12 SDR', bands: null },
        'VIIRS-M13-SDR': { name: 'VIIRS M13 SDR', bands: null },
        'VIIRS-M14-SDR': { name: 'VIIRS M14 SDR', bands: null },
        'VIIRS-M15-SDR': { name: 'VIIRS M15 SDR', bands: null },
        'VIIRS-M16-SDR': { name: 'VIIRS M16 SDR', bands: null },
        'VIIRS-M2-SDR': { name: 'VIIRS M2 SDR', bands: null },
        'VIIRS-M3-SDR': { name: 'VIIRS M3 SDR', bands: null },
        'VIIRS-M4-SDR': { name: 'VIIRS M4 SDR', bands: null },
        'VIIRS-M5-SDR': { name: 'VIIRS M5 SDR', bands: null },
        'VIIRS-M6-SDR': { name: 'VIIRS M6 SDR', bands: null },
        'VIIRS-M7-SDR': { name: 'VIIRS M7 SDR', bands: null },
        'VIIRS-M8-SDR': { name: 'VIIRS M8 SDR', bands: null },
        'VIIRS-M9-SDR': { name: 'VIIRS M9 SDR', bands: null },
        'VIIRS-MOD-GEO-TC': { name: 'VIIRS MOD GEO TC', bands: null },
        'VIIRS-MOD-GEO': { name: 'VIIRS MOD GEO', bands: null },
        'VIIRS-MOD-GTM-EDR-GEO': { name: 'VIIRS MOD GTM EDR GEO', bands: null },
        'VIIRS-NCC-EDR-GEO': { name: 'VIIRS NCC EDR GEO', bands: null },
        'VIIRS-NCC-EDR': { name: 'VIIRS NCC EDR', bands: null },
        'VIIRS_EFIRE_VIIRSI_EDR': { name: 'VIIRS EFIRE VIIRSI EDR', bands: null },
        'VIIRS_I_IMG_EDR_TIP': { name: 'VIIRS I IMG EDR TIP', bands: null },
        'VIIRS_M1_EDR_TIP': { name: 'VIIRS M1 EDR TIP', bands: null },
        'VIIRS_NCC_EDR_TIPC10_KNES': { name: 'VIIRS NCC EDR TIPC10 KNES', bands: null },
        'VIIRS_NCC_EDR_TIPI10_KNES': { name: 'VIIRS NCC EDR TIPI10 KNES', bands: null },
        'VIIRS_NCC_EDR_TIPQ10_KNES': { name: 'VIIRS NCC EDR TIPQ10 KNES', bands: null },
        'VIIRS_SurfaceReflectance_EDR': { name: 'VIIRS Surface Reflectance EDR', bands: null },
        'VIIRS_VFM_MWS_MOSAIC': { name: 'VIIRS VFM MWS Mosaic', bands: null },
        'VI_BWKL_GLB': { name: 'VI BWKL Global', bands: null },
        'VI_BWKL_REG': { name: 'VI BWKL Regional', bands: null },
        'VI_DLY_GLB': { name: 'VI Daily Global', bands: null },
        'VI_DLY_REG': { name: 'VI Daily Regional', bands: null },
        'VI_WKL_GLB': { name: 'VI Weekly Global', bands: null },
        'VI_WKL_REG': { name: 'VI Weekly Regional', bands: null }
      }
    },
    'NOAA-21': {
      bucket: 'noaa-nesdis-n21-pds',
      products: {
        'ATMS-SCIENCE-RDR': { name: 'ATMS Science RDR', bands: null },
        'ATMS-SDR-GEO': { name: 'ATMS SDR GEO', bands: null },
        'ATMS-SDR': { name: 'ATMS SDR', bands: null },
        'ATMS-SFR': { name: 'ATMS SFR', bands: null },
        'ATMS-TDR': { name: 'ATMS TDR', bands: null },
        'ATMS_BUFR': { name: 'ATMS BUFR', bands: null },
        'CRIS-SCIENCE-RDR': { name: 'CRIS Science RDR', bands: null },
        'CrIS-FS-SDR': { name: 'CrIS FS SDR', bands: null },
        'CrIS-SDR-GEO': { name: 'CrIS SDR GEO', bands: null },
        'GRIDDED_VIIRS_LSA_DLY': { name: 'Gridded VIIRS LSA Daily', bands: null },
        'GRIDDED_VIIRS_LST_D': { name: 'Gridded VIIRS LST Day', bands: null },
        'GRIDDED_VIIRS_LST_N': { name: 'Gridded VIIRS LST Night', bands: null },
        'GVF_GLB': { name: 'GVF Global', bands: null },
        'GVF_REG': { name: 'GVF Regional', bands: null },
        'JPSSRR_LST': { name: 'JPSSRR LST', bands: null },
        'JPSSRR_SnowCover': { name: 'JPSSRR Snow Cover', bands: null },
        'JPSSRR_SurfAlb': { name: 'JPSSRR Surface Albedo', bands: null },
        'L2VR2YCW': { name: 'L2VR2YCW', bands: null },
        'NPR_MIRS_IMG': { name: 'NPR MIRS IMG', bands: null },
        'NPR_MIRS_IMG_33min': { name: 'NPR MIRS IMG 33min', bands: null },
        'NPR_MIRS_SND': { name: 'NPR MIRS SND', bands: null },
        'NPR_MIRS_SND_33min': { name: 'NPR MIRS SND 33min', bands: null },
        'NUCAPS-EDR': { name: 'NUCAPS EDR', bands: null },
        'NUCAPS_C0431_BUFR': { name: 'NUCAPS C0431 BUFR', bands: null },
        'NUCAPS_C2211_BUFR': { name: 'NUCAPS C2211 BUFR', bands: null },
        'OMPS-NP-GEO': { name: 'OMPS NP GEO', bands: null },
        'OMPS-NP-SDR': { name: 'OMPS NP SDR', bands: null },
        'OMPS-TC-GEO': { name: 'OMPS TC GEO', bands: null },
        'OMPS-TC-SDR': { name: 'OMPS TC SDR', bands: null },
        'OMPS_V8TOZ': { name: 'OMPS V8TOZ', bands: null },
        'SFR_ATMS': { name: 'SFR ATMS', bands: null },
        'TLE-AUX': { name: 'TLE AUX', bands: null },
        'VIIRS-DNB-GEO': { name: 'VIIRS DNB GEO', bands: null },
        'VIIRS-DNB-SDR': { name: 'VIIRS DNB SDR', bands: null },
        'VIIRS-I1-IMG-EDR': { name: 'VIIRS I1 IMG EDR', bands: null },
        'VIIRS-I1-SDR': { name: 'VIIRS I1 SDR', bands: null },
        'VIIRS-I2-IMG-EDR': { name: 'VIIRS I2 IMG EDR', bands: null },
        'VIIRS-I2-SDR': { name: 'VIIRS I2 SDR', bands: null },
        'VIIRS-I3-IMG-EDR': { name: 'VIIRS I3 IMG EDR', bands: null },
        'VIIRS-I3-SDR': { name: 'VIIRS I3 SDR', bands: null },
        'VIIRS-I4-IMG-EDR': { name: 'VIIRS I4 IMG EDR', bands: null },
        'VIIRS-I4-SDR': { name: 'VIIRS I4 SDR', bands: null },
        'VIIRS-I5-IMG-EDR': { name: 'VIIRS I5 IMG EDR', bands: null },
        'VIIRS-I5-SDR': { name: 'VIIRS I5 SDR', bands: null },
        'VIIRS-IMG-GEO-TC': { name: 'VIIRS IMG GEO TC', bands: null },
        'VIIRS-IMG-GEO': { name: 'VIIRS IMG GEO', bands: null },
        'VIIRS-IMG-GTM-EDR-GEO': { name: 'VIIRS IMG GTM EDR GEO', bands: null },
        'VIIRS-JRR-ADP': { name: 'VIIRS JRR ADP', bands: null },
        'VIIRS-JRR-AOD': { name: 'VIIRS JRR AOD', bands: null },
        'VIIRS-JRR-CloudBase': { name: 'VIIRS JRR Cloud Base', bands: null },
        'VIIRS-JRR-CloudCoverLayers': { name: 'VIIRS JRR Cloud Cover Layers', bands: null },
        'VIIRS-JRR-CloudDCOMP': { name: 'VIIRS JRR Cloud DCOMP', bands: null },
        'VIIRS-JRR-CloudHeight': { name: 'VIIRS JRR Cloud Height', bands: null },
        'VIIRS-JRR-CloudMask': { name: 'VIIRS JRR Cloud Mask', bands: null },
        'VIIRS-JRR-CloudNCOMP': { name: 'VIIRS JRR Cloud NCOMP', bands: null },
        'VIIRS-JRR-CloudPhase': { name: 'VIIRS JRR Cloud Phase', bands: null },
        'VIIRS-JRR-IceAge': { name: 'VIIRS JRR Ice Age', bands: null },
        'VIIRS-JRR-IceConcentration': { name: 'VIIRS JRR Ice Concentration', bands: null },
        'VIIRS-JRR-VolcanicAsh': { name: 'VIIRS JRR Volcanic Ash', bands: null },
        'VIIRS-M1-SDR': { name: 'VIIRS M1 SDR', bands: null },
        'VIIRS-M10-SDR': { name: 'VIIRS M10 SDR', bands: null },
        'VIIRS-M11-SDR': { name: 'VIIRS M11 SDR', bands: null },
        'VIIRS-M12-SDR': { name: 'VIIRS M12 SDR', bands: null },
        'VIIRS-M13-SDR': { name: 'VIIRS M13 SDR', bands: null },
        'VIIRS-M14-SDR': { name: 'VIIRS M14 SDR', bands: null },
        'VIIRS-M15-SDR': { name: 'VIIRS M15 SDR', bands: null },
        'VIIRS-M16-SDR': { name: 'VIIRS M16 SDR', bands: null },
        'VIIRS-M2-SDR': { name: 'VIIRS M2 SDR', bands: null },
        'VIIRS-M3-SDR': { name: 'VIIRS M3 SDR', bands: null },
        'VIIRS-M4-SDR': { name: 'VIIRS M4 SDR', bands: null },
        'VIIRS-M5-SDR': { name: 'VIIRS M5 SDR', bands: null },
        'VIIRS-M6-SDR': { name: 'VIIRS M6 SDR', bands: null },
        'VIIRS-M7-SDR': { name: 'VIIRS M7 SDR', bands: null },
        'VIIRS-M8-SDR': { name: 'VIIRS M8 SDR', bands: null },
        'VIIRS-M9-SDR': { name: 'VIIRS M9 SDR', bands: null },
        'VIIRS-MOD-GEO-TC': { name: 'VIIRS MOD GEO TC', bands: null },
        'VIIRS-MOD-GEO': { name: 'VIIRS MOD GEO', bands: null },
        'VIIRS-MOD-GTM-EDR-GEO': { name: 'VIIRS MOD GTM EDR GEO', bands: null },
        'VIIRS-NCC-EDR-GEO': { name: 'VIIRS NCC EDR GEO', bands: null },
        'VIIRS-NCC-EDR': { name: 'VIIRS NCC EDR', bands: null },
        'VIIRS_EFIRE_VIIRSI_EDR': { name: 'VIIRS EFIRE VIIRSI EDR', bands: null },
        'VIIRS_I_IMG_EDR_TIP': { name: 'VIIRS I IMG EDR TIP', bands: null },
        'VIIRS_M1_EDR_TIP': { name: 'VIIRS M1 EDR TIP', bands: null },
        'VIIRS_NCC_EDR_TIPC10_KNES': { name: 'VIIRS NCC EDR TIPC10 KNES', bands: null },
        'VIIRS_NCC_EDR_TIPI10_KNES': { name: 'VIIRS NCC EDR TIPI10 KNES', bands: null },
        'VIIRS_NCC_EDR_TIPQ10_KNES': { name: 'VIIRS NCC EDR TIPQ10 KNES', bands: null },
        'VIIRS_SurfaceReflectance_EDR': { name: 'VIIRS Surface Reflectance EDR', bands: null },
        'VIIRS_VFM_MWS_MOSAIC': { name: 'VIIRS VFM MWS Mosaic', bands: null },
        'VI_BWKL_GLB': { name: 'VI BWKL Global', bands: null },
        'VI_BWKL_REG': { name: 'VI BWKL Regional', bands: null },
        'VI_DLY_GLB': { name: 'VI Daily Global', bands: null },
        'VI_DLY_REG': { name: 'VI Daily Regional', bands: null },
        'VI_WKL_GLB': { name: 'VI Weekly Global', bands: null },
        'VI_WKL_REG': { name: 'VI Weekly Regional', bands: null }
      }
    }
  },

  // Band information for GOES
  bandInfo: {
    'C01': { name: 'Blue', wavelength: '0.47 µm' },
    'C02': { name: 'Red', wavelength: '0.64 µm' },
    'C03': { name: 'Vegetation', wavelength: '0.86 µm' },
    'C04': { name: 'Cirrus', wavelength: '1.37 µm' },
    'C05': { name: 'SWIR', wavelength: '1.6 µm' },
    'C06': { name: 'SWIR', wavelength: '2.2 µm' },
    'C07': { name: 'Water Vapor', wavelength: '3.9 µm' },
    'C08': { name: 'Water Vapor', wavelength: '6.2 µm' },
    'C09': { name: 'Water Vapor', wavelength: '6.9 µm' },
    'C10': { name: 'SO2', wavelength: '7.3 µm' },
    'C11': { name: 'Ash', wavelength: '8.4 µm' },
    'C12': { name: 'Ash', wavelength: '9.6 µm' },
    'C13': { name: 'Clean IR', wavelength: '10.3 µm' },
    'C14': { name: 'Longwave IR', wavelength: '11.2 µm' },
    'C15': { name: 'Longwave IR', wavelength: '12.3 µm' },
    'C16': { name: 'CO2', wavelength: '13.3 µm' }
  }
};

if (typeof module !== 'undefined' && module.exports) {
  module.exports = CONFIG;
}
// expose ABI_BANDS on CONFIG for compatibility
CONFIG.ABI_BANDS = ABI_BANDS;
