/**
 * Configuration for GOES/Suomi NPP Data Downloader
 * Includes ALL available products from NOAA S3 buckets
 */

// Standard ABI band codes used for many ABI L1b/L2 products
const ABI_BANDS = ['C01','C02','C03','C04','C05','C06','C07','C08','C09','C10','C11','C12','C13','C14','C15','C16'];

const CONFIG = {
  // Satellites and their products
  satellites: {
    'GOES-16': {
      bucket: 'noaa-goes16',
      products: {
        'ABI-Flood-Day-Shapefiles': { name: 'ABI Flood Day Shapefiles', bands: null },
        'ABI-Flood-Day-TIF': { name: 'ABI Flood Day TIF', bands: null },
        'ABI-Flood-Day': { name: 'ABI Flood Day', bands: null },
        'ABI-Flood-Hourly-Shapefiles': { name: 'ABI Flood Hourly Shapefiles', bands: null },
        'ABI-Flood-Hourly-TIF': { name: 'ABI Flood Hourly TIF', bands: null },
        'ABI-Flood-Hourly': { name: 'ABI Flood Hourly', bands: null },
        'ABI-L1b-RadC': { name: 'ABI L1b Radiance (CONUS)', bands: ABI_BANDS },
        'ABI-L1b-RadF': { name: 'ABI L1b Radiance (Full Disk)', bands: ABI_BANDS },
        'ABI-L1b-RadM': { name: 'ABI L1b Radiance (Mesoscale)', bands: ABI_BANDS },
        'ABI-L2-ACHA2KMC': { name: 'ABI L2 ACHA2K (CONUS)', bands: ABI_BANDS },
        'ABI-L2-ACHA2KMF': { name: 'ABI L2 ACHA2K (Full)', bands: ABI_BANDS },
        'ABI-L2-ACHA2KMM': { name: 'ABI L2 ACHA2K (Mesoscale)', bands: ABI_BANDS },
        'ABI-L2-ACHAC': { name: 'ABI L2 ACHA (CONUS)', bands: ABI_BANDS },
        'ABI-L2-ACHAF': { name: 'ABI L2 ACHA (Full)', bands: ABI_BANDS },
        'ABI-L2-ACHAM': { name: 'ABI L2 ACHA (Mesoscale)', bands: ABI_BANDS },
        'ABI-L2-ACHP2KMC': { name: 'ABI L2 ACHP2K (CONUS)', bands: ABI_BANDS },
        'ABI-L2-ACHP2KMF': { name: 'ABI L2 ACHP2K (Full)', bands: ABI_BANDS },
        'ABI-L2-ACHP2KMM': { name: 'ABI L2 ACHP2K (Mesoscale)', bands: ABI_BANDS },
        'ABI-L2-ACHTF': { name: 'ABI L2 ACH Type F', bands: ABI_BANDS },
        'ABI-L2-ACHTM': { name: 'ABI L2 ACH Type M', bands: ABI_BANDS },
        'ABI-L2-ACMC': { name: 'ABI L2 ACM (CONUS)', bands: ABI_BANDS },
        'ABI-L2-ACMF': { name: 'ABI L2 ACM (Full)', bands: ABI_BANDS },
        'ABI-L2-ACMM': { name: 'ABI L2 ACM (Mesoscale)', bands: ABI_BANDS },
        'ABI-L2-ACTPC': { name: 'ABI L2 ACTP (CONUS)', bands: ABI_BANDS },
        'ABI-L2-ACTPF': { name: 'ABI L2 ACTP (Full)', bands: ABI_BANDS },
        'ABI-L2-ACTPM': { name: 'ABI L2 ACTP (Mesoscale)', bands: ABI_BANDS },
        'ABI-L2-ADPC': { name: 'ABI L2 ADP (CONUS)', bands: ABI_BANDS },
        'ABI-L2-ADPF': { name: 'ABI L2 ADP (Full)', bands: ABI_BANDS },
        'ABI-L2-ADPM': { name: 'ABI L2 ADP (Mesoscale)', bands: ABI_BANDS },
        'ABI-L2-AICEF': { name: 'ABI L2 AICE (Full)', bands: ABI_BANDS },
        'ABI-L2-AITAF': { name: 'ABI L2 AITA (Full)', bands: ABI_BANDS },
        'ABI-L2-AODC': { name: 'ABI L2 AOD (CONUS)', bands: ABI_BANDS },
        'ABI-L2-AODF': { name: 'ABI L2 AOD (Full)', bands: ABI_BANDS },
        'ABI-L2-BRFC': { name: 'ABI L2 BRF (CONUS)', bands: ABI_BANDS },
        'ABI-L2-BRFF': { name: 'ABI L2 BRF (Full)', bands: ABI_BANDS },
        'ABI-L2-BRFM': { name: 'ABI L2 BRF (Mesoscale)', bands: ABI_BANDS },
        'ABI-L2-CCLC': { name: 'ABI L2 CCLC (CONUS)', bands: ABI_BANDS },
        'ABI-L2-CCLF': { name: 'ABI L2 CCLC (Full)', bands: ABI_BANDS },
        'ABI-L2-CCLM': { name: 'ABI L2 CCLC (Mesoscale)', bands: ABI_BANDS },
        'ABI-L2-CMIPC': { name: 'ABI L2 CMIP (CONUS)', bands: ABI_BANDS },
        'ABI-L2-CMIPF': { name: 'ABI L2 CMIP (Full)', bands: ABI_BANDS },
        'ABI-L2-CMIPM': { name: 'ABI L2 CMIP (Mesoscale)', bands: ABI_BANDS },
        'ABI-L2-COD2KMF': { name: 'ABI L2 COD2KM (Full)', bands: ABI_BANDS },
        'ABI-L2-CODC': { name: 'ABI L2 COD (CONUS)', bands: ABI_BANDS },
        'ABI-L2-CODF': { name: 'ABI L2 COD (Full)', bands: ABI_BANDS },
        'ABI-L2-CPSC': { name: 'ABI L2 CPSC (CONUS)', bands: ABI_BANDS },
        'ABI-L2-CPSF': { name: 'ABI L2 CPSC (Full)', bands: ABI_BANDS },
        'ABI-L2-CPSM': { name: 'ABI L2 CPSC (Mesoscale)', bands: ABI_BANDS },
        'ABI-L2-CTPC': { name: 'ABI L2 CTPC (CONUS)', bands: ABI_BANDS },
        'ABI-L2-CTPF': { name: 'ABI L2 CTPC (Full)', bands: ABI_BANDS },
        'ABI-L2-DMWC': { name: 'ABI L2 DMW (CONUS)', bands: ABI_BANDS },
        'ABI-L2-DMWF': { name: 'ABI L2 DMW (Full)', bands: ABI_BANDS },
        'ABI-L2-DMWM': { name: 'ABI L2 DMW (Mesoscale)', bands: ABI_BANDS },
        'ABI-L2-DMWVC': { name: 'ABI L2 DMWV (CONUS)', bands: ABI_BANDS },
        'ABI-L2-DMWVF': { name: 'ABI L2 DMWV (Full)', bands: ABI_BANDS },
        'ABI-L2-DMWVM': { name: 'ABI L2 DMWV (Mesoscale)', bands: ABI_BANDS },
        'ABI-L2-DSIC': { name: 'ABI L2 DSIC (CONUS)', bands: ABI_BANDS },
        'ABI-L2-DSIF': { name: 'ABI L2 DSIC (Full)', bands: ABI_BANDS },
        'ABI-L2-DSIM': { name: 'ABI L2 DSIC (Mesoscale)', bands: ABI_BANDS },
        'ABI-L2-DSRC': { name: 'ABI L2 DSRC (CONUS)', bands: ABI_BANDS },
        'ABI-L2-DSRF': { name: 'ABI L2 DSRC (Full)', bands: ABI_BANDS },
        'ABI-L2-DSRM': { name: 'ABI L2 DSRC (Mesoscale)', bands: ABI_BANDS },
        'ABI-L2-FDCC': { name: 'ABI L2 FDCC (CONUS)', bands: ABI_BANDS },
        'ABI-L2-FDCF': { name: 'ABI L2 FDCC (Full)', bands: ABI_BANDS },
        'ABI-L2-FDCM': { name: 'ABI L2 FDCC (Mesoscale)', bands: ABI_BANDS },
        'ABI-L2-FSCC': { name: 'ABI L2 FSCC (CONUS)', bands: ABI_BANDS },
        'ABI-L2-FSCF': { name: 'ABI L2 FSCC (Full)', bands: ABI_BANDS },
        'ABI-L2-FSCM': { name: 'ABI L2 FSCC (Mesoscale)', bands: ABI_BANDS },
        'ABI-L2-LSAC': { name: 'ABI L2 LSAC (CONUS)', bands: ABI_BANDS },
        'ABI-L2-LSAF': { name: 'ABI L2 LSA (Full)', bands: ABI_BANDS },
        'ABI-L2-LSAM': { name: 'ABI L2 LSA (Mesoscale)', bands: ABI_BANDS },
        'ABI-L2-LST2KMF': { name: 'ABI L2 LST2KM (Full)', bands: ABI_BANDS },
        'ABI-L2-LSTC': { name: 'ABI L2 LST (CONUS)', bands: ABI_BANDS },
        'ABI-L2-LSTF': { name: 'ABI L2 LST (Full)', bands: ABI_BANDS },
        'ABI-L2-LSTM': { name: 'ABI L2 LST (Mesoscale)', bands: ABI_BANDS },
        'ABI-L2-LVMPC': { name: 'ABI L2 LVMP (CONUS)', bands: ABI_BANDS },
        'ABI-L2-LVMPF': { name: 'ABI L2 LVMP (Full)', bands: ABI_BANDS },
        'ABI-L2-LVMPM': { name: 'ABI L2 LVMP (Mesoscale)', bands: ABI_BANDS },
        'ABI-L2-LVTPC': { name: 'ABI L2 LVTP (CONUS)', bands: ABI_BANDS },
        'ABI-L2-LVTPF': { name: 'ABI L2 LVTP (Full)', bands: ABI_BANDS },
        'ABI-L2-LVTPM': { name: 'ABI L2 LVTP (Mesoscale)', bands: ABI_BANDS },
        'ABI-L2-MCMIPC': { name: 'ABI L2 MCMIP (CONUS)', bands: ABI_BANDS },
        'ABI-L2-MCMIPF': { name: 'ABI L2 MCMIP (Full)', bands: ABI_BANDS },
        'ABI-L2-MCMIPM': { name: 'ABI L2 MCMIP (Mesoscale)', bands: ABI_BANDS },
        'ABI-L2-PARF': { name: 'ABI L2 PAR (Full)', bands: ABI_BANDS },
        'ABI-L2-RRQPEF': { name: 'ABI L2 RRQPE (Full)', bands: ABI_BANDS },
        'ABI-L2-RSRC': { name: 'ABI L2 RSRC (CONUS)', bands: ABI_BANDS },
        'ABI-L2-RSRF': { name: 'ABI L2 RSR (Full)', bands: ABI_BANDS },
        'ABI-L2-SSTF': { name: 'ABI L2 SST (Full)', bands: ABI_BANDS },
        'ABI-L2-TPWC': { name: 'ABI L2 TPW (CONUS)', bands: ABI_BANDS },
        'ABI-L2-TPWF': { name: 'ABI L2 TPW (Full)', bands: ABI_BANDS },
        'ABI-L2-TPWM': { name: 'ABI L2 TPW (Mesoscale)', bands: ABI_BANDS },
        'EXIS-L1b-SFEU': { name: 'EXIS L1b SFEU', bands: null },
        'EXIS-L1b-SFXR': { name: 'EXIS L1b SFXR', bands: null },
        'GLM-L2-LCFA': { name: 'GLM L2 LCFA', bands: null },
        'MAG-L1b-GEOF': { name: 'MAG L1b GEOF', bands: null },
        'SEIS-L1b-EHIS': { name: 'SEIS L1b EHIS', bands: null },
        'SEIS-L1b-MPSH': { name: 'SEIS L1b MPSH', bands: null },
        'SEIS-L1b-MPSL': { name: 'SEIS L1b MPSL', bands: null },
        'SEIS-L1b-SGPS': { name: 'SEIS L1b SGPS', bands: null },
        'SUVI-L1b-Fe093': { name: 'SUVI L1b Fe093', bands: null },
        'SUVI-L1b-Fe131': { name: 'SUVI L1b Fe131', bands: null },
        'SUVI-L1b-Fe171': { name: 'SUVI L1b Fe171', bands: null },
        'SUVI-L1b-Fe195': { name: 'SUVI L1b Fe195', bands: null },
        'SUVI-L1b-Fe284': { name: 'SUVI L1b Fe284', bands: null },
        'SUVI-L1b-He303': { name: 'SUVI L1b He303', bands: null }
      }
    },
    'GOES-17': {
      bucket: 'noaa-goes17',
      products: {
        'ABI-Flood-Day-Shapefiles': { name: 'ABI Flood Day Shapefiles', bands: null },
        'ABI-Flood-Day-TIF': { name: 'ABI Flood Day TIF', bands: null },
        'ABI-Flood-Day': { name: 'ABI Flood Day', bands: null },
        'ABI-Flood-Hourly-Shapefiles': { name: 'ABI Flood Hourly Shapefiles', bands: null },
        'ABI-Flood-Hourly-TIF': { name: 'ABI Flood Hourly TIF', bands: null },
        'ABI-Flood-Hourly': { name: 'ABI Flood Hourly', bands: null },
        'ABI-L1b-RadC': { name: 'ABI L1b Radiance (CONUS)', bands: ABI_BANDS },
        'ABI-L1b-RadF': { name: 'ABI L1b Radiance (Full Disk)', bands: ABI_BANDS },
        'ABI-L1b-RadM': { name: 'ABI L1b Radiance (Mesoscale)', bands: ABI_BANDS },
        'ABI-L2-ACHA2KMC': { name: 'ABI L2 ACHA2K (CONUS)', bands: ABI_BANDS },
        'ABI-L2-ACHA2KMF': { name: 'ABI L2 ACHA2K (Full)', bands: ABI_BANDS },
        'ABI-L2-ACHA2KMM': { name: 'ABI L2 ACHA2K (Mesoscale)', bands: ABI_BANDS },
        'ABI-L2-ACHAC': { name: 'ABI L2 ACHA (CONUS)', bands: ABI_BANDS },
        'ABI-L2-ACHAF': { name: 'ABI L2 ACHA (Full)', bands: ABI_BANDS },
        'ABI-L2-ACHAM': { name: 'ABI L2 ACHA (Mesoscale)', bands: ABI_BANDS },
        'ABI-L2-ACHP2KMC': { name: 'ABI L2 ACHP2K (CONUS)', bands: ABI_BANDS },
        'ABI-L2-ACHP2KMF': { name: 'ABI L2 ACHP2K (Full)', bands: ABI_BANDS },
        'ABI-L2-ACHP2KMM': { name: 'ABI L2 ACHP2K (Mesoscale)', bands: ABI_BANDS },
        'ABI-L2-ACHTF': { name: 'ABI L2 ACH Type F', bands: ABI_BANDS },
        'ABI-L2-ACHTM': { name: 'ABI L2 ACH Type M', bands: ABI_BANDS },
        'ABI-L2-ACMC': { name: 'ABI L2 ACM (CONUS)', bands: ABI_BANDS },
        'ABI-L2-ACMF': { name: 'ABI L2 ACM (Full)', bands: ABI_BANDS },
        'ABI-L2-ACMM': { name: 'ABI L2 ACM (Mesoscale)', bands: ABI_BANDS },
        'ABI-L2-ACTPC': { name: 'ABI L2 ACTP (CONUS)', bands: ABI_BANDS },
        'ABI-L2-ACTPF': { name: 'ABI L2 ACTP (Full)', bands: ABI_BANDS },
        'ABI-L2-ACTPM': { name: 'ABI L2 ACTP (Mesoscale)', bands: ABI_BANDS },
        'ABI-L2-ADPC': { name: 'ABI L2 ADP (CONUS)', bands: ABI_BANDS },
        'ABI-L2-ADPF': { name: 'ABI L2 ADP (Full)', bands: ABI_BANDS },
        'ABI-L2-ADPM': { name: 'ABI L2 ADP (Mesoscale)', bands: ABI_BANDS },
        'ABI-L2-AICEF': { name: 'ABI L2 AICE (Full)', bands: ABI_BANDS },
        'ABI-L2-AITAF': { name: 'ABI L2 AITA (Full)', bands: ABI_BANDS },
        'ABI-L2-AODC': { name: 'ABI L2 AOD (CONUS)', bands: ABI_BANDS },
        'ABI-L2-AODF': { name: 'ABI L2 AOD (Full)', bands: ABI_BANDS },
        'ABI-L2-BRFC': { name: 'ABI L2 BRF (CONUS)', bands: ABI_BANDS },
        'ABI-L2-BRFF': { name: 'ABI L2 BRF (Full)', bands: ABI_BANDS },
        'ABI-L2-BRFM': { name: 'ABI L2 BRF (Mesoscale)', bands: ABI_BANDS },
        'ABI-L2-CCLC': { name: 'ABI L2 CCLC (CONUS)', bands: ABI_BANDS },
        'ABI-L2-CCLF': { name: 'ABI L2 CCLC (Full)', bands: ABI_BANDS },
        'ABI-L2-CCLM': { name: 'ABI L2 CCLC (Mesoscale)', bands: ABI_BANDS },
        'ABI-L2-CMIPC': { name: 'ABI L2 CMIP (CONUS)', bands: ABI_BANDS },
        'ABI-L2-CMIPF': { name: 'ABI L2 CMIP (Full)', bands: ABI_BANDS },
        'ABI-L2-CMIPM': { name: 'ABI L2 CMIP (Mesoscale)', bands: ABI_BANDS },
        'ABI-L2-COD2KMF': { name: 'ABI L2 COD2KM (Full)', bands: ABI_BANDS },
        'ABI-L2-CODC': { name: 'ABI L2 COD (CONUS)', bands: ABI_BANDS },
        'ABI-L2-CODF': { name: 'ABI L2 COD (Full)', bands: ABI_BANDS },
        'ABI-L2-CPSC': { name: 'ABI L2 CPSC (CONUS)', bands: ABI_BANDS },
        'ABI-L2-CPSF': { name: 'ABI L2 CPSC (Full)', bands: ABI_BANDS },
        'ABI-L2-CPSM': { name: 'ABI L2 CPSC (Mesoscale)', bands: ABI_BANDS },
        'ABI-L2-CTPC': { name: 'ABI L2 CTPC (CONUS)', bands: ABI_BANDS },
        'ABI-L2-CTPF': { name: 'ABI L2 CTPC (Full)', bands: ABI_BANDS },
        'ABI-L2-DMWC': { name: 'ABI L2 DMW (CONUS)', bands: ABI_BANDS },
        'ABI-L2-DMWF': { name: 'ABI L2 DMW (Full)', bands: ABI_BANDS },
        'ABI-L2-DMWM': { name: 'ABI L2 DMW (Mesoscale)', bands: ABI_BANDS },
        'ABI-L2-DMWVC': { name: 'ABI L2 DMWV (CONUS)', bands: ABI_BANDS },
        'ABI-L2-DMWVF': { name: 'ABI L2 DMWV (Full)', bands: ABI_BANDS },
        'ABI-L2-DMWVM': { name: 'ABI L2 DMWV (Mesoscale)', bands: ABI_BANDS },
        'ABI-L2-DSIC': { name: 'ABI L2 DSIC (CONUS)', bands: ABI_BANDS },
        'ABI-L2-DSIF': { name: 'ABI L2 DSIC (Full)', bands: ABI_BANDS },
        'ABI-L2-DSIM': { name: 'ABI L2 DSIC (Mesoscale)', bands: ABI_BANDS },
        'ABI-L2-DSRC': { name: 'ABI L2 DSRC (CONUS)', bands: ABI_BANDS },
        'ABI-L2-DSRF': { name: 'ABI L2 DSRC (Full)', bands: ABI_BANDS },
        'ABI-L2-DSRM': { name: 'ABI L2 DSRC (Mesoscale)', bands: ABI_BANDS },
        'ABI-L2-FDCC': { name: 'ABI L2 FDCC (CONUS)', bands: ABI_BANDS },
        'ABI-L2-FDCF': { name: 'ABI L2 FDCC (Full)', bands: ABI_BANDS },
        'ABI-L2-FDCM': { name: 'ABI L2 FDCC (Mesoscale)', bands: ABI_BANDS },
        'ABI-L2-FSCC': { name: 'ABI L2 FSCC (CONUS)', bands: ABI_BANDS },
        'ABI-L2-FSCF': { name: 'ABI L2 FSCC (Full)', bands: ABI_BANDS },
        'ABI-L2-FSCM': { name: 'ABI L2 FSCC (Mesoscale)', bands: ABI_BANDS },
        'ABI-L2-LSAC': { name: 'ABI L2 LSAC (CONUS)', bands: ABI_BANDS },
        'ABI-L2-LSAF': { name: 'ABI L2 LSA (Full)', bands: ABI_BANDS },
        'ABI-L2-LSAM': { name: 'ABI L2 LSA (Mesoscale)', bands: ABI_BANDS },
        'ABI-L2-LST2KMF': { name: 'ABI L2 LST2KM (Full)', bands: ABI_BANDS },
        'ABI-L2-LSTC': { name: 'ABI L2 LST (CONUS)', bands: ABI_BANDS },
        'ABI-L2-LSTF': { name: 'ABI L2 LST (Full)', bands: ABI_BANDS },
        'ABI-L2-LSTM': { name: 'ABI L2 LST (Mesoscale)', bands: ABI_BANDS },
        'ABI-L2-LVMPC': { name: 'ABI L2 LVMP (CONUS)', bands: ABI_BANDS },
        'ABI-L2-LVMPF': { name: 'ABI L2 LVMP (Full)', bands: ABI_BANDS },
        'ABI-L2-LVMPM': { name: 'ABI L2 LVMP (Mesoscale)', bands: ABI_BANDS },
        'ABI-L2-LVTPC': { name: 'ABI L2 LVTP (CONUS)', bands: ABI_BANDS },
        'ABI-L2-LVTPF': { name: 'ABI L2 LVTP (Full)', bands: ABI_BANDS },
        'ABI-L2-LVTPM': { name: 'ABI L2 LVTP (Mesoscale)', bands: ABI_BANDS },
        'ABI-L2-MCMIPC': { name: 'ABI L2 MCMIP (CONUS)', bands: ABI_BANDS },
        'ABI-L2-MCMIPF': { name: 'ABI L2 MCMIP (Full)', bands: ABI_BANDS },
        'ABI-L2-MCMIPM': { name: 'ABI L2 MCMIP (Mesoscale)', bands: ABI_BANDS },
        'ABI-L2-PARF': { name: 'ABI L2 PAR (Full)', bands: ABI_BANDS },
        'ABI-L2-RRQPEF': { name: 'ABI L2 RRQPE (Full)', bands: ABI_BANDS },
        'ABI-L2-RSRC': { name: 'ABI L2 RSRC (CONUS)', bands: ABI_BANDS },
        'ABI-L2-RSRF': { name: 'ABI L2 RSR (Full)', bands: ABI_BANDS },
        'ABI-L2-SSTF': { name: 'ABI L2 SST (Full)', bands: ABI_BANDS },
        'ABI-L2-TPWC': { name: 'ABI L2 TPW (CONUS)', bands: ABI_BANDS },
        'ABI-L2-TPWF': { name: 'ABI L2 TPW (Full)', bands: ABI_BANDS },
        'ABI-L2-TPWM': { name: 'ABI L2 TPW (Mesoscale)', bands: ABI_BANDS },
        'EXIS-L1b-SFEU': { name: 'EXIS L1b SFEU', bands: null },
        'EXIS-L1b-SFXR': { name: 'EXIS L1b SFXR', bands: null },
        'GLM-L2-LCFA': { name: 'GLM L2 LCFA', bands: null },
        'MAG-L1b-GEOF': { name: 'MAG L1b GEOF', bands: null },
        'SEIS-L1b-EHIS': { name: 'SEIS L1b EHIS', bands: null },
        'SEIS-L1b-MPSH': { name: 'SEIS L1b MPSH', bands: null },
        'SEIS-L1b-MPSL': { name: 'SEIS L1b MPSL', bands: null },
        'SEIS-L1b-SGPS': { name: 'SEIS L1b SGPS', bands: null },
        'SUVI-L1b-Fe093': { name: 'SUVI L1b Fe093', bands: null },
        'SUVI-L1b-Fe131': { name: 'SUVI L1b Fe131', bands: null },
        'SUVI-L1b-Fe171': { name: 'SUVI L1b Fe171', bands: null },
        'SUVI-L1b-Fe195': { name: 'SUVI L1b Fe195', bands: null },
        'SUVI-L1b-Fe284': { name: 'SUVI L1b Fe284', bands: null },
        'SUVI-L1b-He303': { name: 'SUVI L1b He303', bands: null }
      }
    },
    'GOES-18': {
      bucket: 'noaa-goes18',
      products: {
        'ABI-Flood-Day-Shapefiles': { name: 'ABI Flood Day Shapefiles', bands: null },
        'ABI-Flood-Day-TIF': { name: 'ABI Flood Day TIF', bands: null },
        'ABI-Flood-Day': { name: 'ABI Flood Day', bands: null },
        'ABI-Flood-Hourly-Shapefiles': { name: 'ABI Flood Hourly Shapefiles', bands: null },
        'ABI-Flood-Hourly-TIF': { name: 'ABI Flood Hourly TIF', bands: null },
        'ABI-Flood-Hourly': { name: 'ABI Flood Hourly', bands: null },
        'ABI-L1b-RadC': { name: 'ABI L1b Radiance (CONUS)', bands: ABI_BANDS },
        'ABI-L1b-RadF': { name: 'ABI L1b Radiance (Full Disk)', bands: ABI_BANDS },
        'ABI-L1b-RadM': { name: 'ABI L1b Radiance (Mesoscale)', bands: ABI_BANDS },
        'ABI-L2-ACHA2KMC': { name: 'ABI L2 ACHA2K (CONUS)', bands: ABI_BANDS },
        'ABI-L2-ACHA2KMF': { name: 'ABI L2 ACHA2K (Full)', bands: ABI_BANDS },
        'ABI-L2-ACHA2KMM': { name: 'ABI L2 ACHA2K (Mesoscale)', bands: ABI_BANDS },
        'ABI-L2-ACHAC': { name: 'ABI L2 ACHA (CONUS)', bands: ABI_BANDS },
        'ABI-L2-ACHAF': { name: 'ABI L2 ACHA (Full)', bands: ABI_BANDS },
        'ABI-L2-ACHAM': { name: 'ABI L2 ACHA (Mesoscale)', bands: ABI_BANDS },
        'ABI-L2-ACHP2KMC': { name: 'ABI L2 ACHP2K (CONUS)', bands: ABI_BANDS },
        'ABI-L2-ACHP2KMF': { name: 'ABI L2 ACHP2K (Full)', bands: ABI_BANDS },
        'ABI-L2-ACHP2KMM': { name: 'ABI L2 ACHP2K (Mesoscale)', bands: ABI_BANDS },
        'ABI-L2-ACHTF': { name: 'ABI L2 ACH Type F', bands: ABI_BANDS },
        'ABI-L2-ACHTM': { name: 'ABI L2 ACH Type M', bands: ABI_BANDS },
        'ABI-L2-ACMC': { name: 'ABI L2 ACM (CONUS)', bands: ABI_BANDS },
        'ABI-L2-ACMF': { name: 'ABI L2 ACM (Full)', bands: ABI_BANDS },
        'ABI-L2-ACMM': { name: 'ABI L2 ACM (Mesoscale)', bands: ABI_BANDS },
        'ABI-L2-ACTPC': { name: 'ABI L2 ACTP (CONUS)', bands: ABI_BANDS },
        'ABI-L2-ACTPF': { name: 'ABI L2 ACTP (Full)', bands: ABI_BANDS },
        'ABI-L2-ACTPM': { name: 'ABI L2 ACTP (Mesoscale)', bands: ABI_BANDS },
        'ABI-L2-ADPC': { name: 'ABI L2 ADP (CONUS)', bands: ABI_BANDS },
        'ABI-L2-ADPF': { name: 'ABI L2 ADP (Full)', bands: ABI_BANDS },
        'ABI-L2-ADPM': { name: 'ABI L2 ADP (Mesoscale)', bands: ABI_BANDS },
        'ABI-L2-AICEF': { name: 'ABI L2 AICE (Full)', bands: ABI_BANDS },
        'ABI-L2-AITAF': { name: 'ABI L2 AITA (Full)', bands: ABI_BANDS },
        'ABI-L2-AODC': { name: 'ABI L2 AOD (CONUS)', bands: ABI_BANDS },
        'ABI-L2-AODF': { name: 'ABI L2 AOD (Full)', bands: ABI_BANDS },
        'ABI-L2-BRFC': { name: 'ABI L2 BRF (CONUS)', bands: ABI_BANDS },
        'ABI-L2-BRFF': { name: 'ABI L2 BRF (Full)', bands: ABI_BANDS },
        'ABI-L2-BRFM': { name: 'ABI L2 BRF (Mesoscale)', bands: ABI_BANDS },
        'ABI-L2-CCLC': { name: 'ABI L2 CCLC (CONUS)', bands: ABI_BANDS },
        'ABI-L2-CCLF': { name: 'ABI L2 CCLC (Full)', bands: ABI_BANDS },
        'ABI-L2-CCLM': { name: 'ABI L2 CCLC (Mesoscale)', bands: ABI_BANDS },
        'ABI-L2-CMIPC': { name: 'ABI L2 CMIP (CONUS)', bands: ABI_BANDS },
        'ABI-L2-CMIPF': { name: 'ABI L2 CMIP (Full)', bands: ABI_BANDS },
        'ABI-L2-CMIPM': { name: 'ABI L2 CMIP (Mesoscale)', bands: ABI_BANDS },
        'ABI-L2-COD2KMF': { name: 'ABI L2 COD2KM (Full)', bands: ABI_BANDS },
        'ABI-L2-CODC': { name: 'ABI L2 COD (CONUS)', bands: ABI_BANDS },
        'ABI-L2-CODF': { name: 'ABI L2 COD (Full)', bands: ABI_BANDS },
        'ABI-L2-CPSC': { name: 'ABI L2 CPSC (CONUS)', bands: ABI_BANDS },
        'ABI-L2-CPSF': { name: 'ABI L2 CPSC (Full)', bands: ABI_BANDS },
        'ABI-L2-CPSM': { name: 'ABI L2 CPSC (Mesoscale)', bands: ABI_BANDS },
        'ABI-L2-CTPC': { name: 'ABI L2 CTPC (CONUS)', bands: ABI_BANDS },
        'ABI-L2-CTPF': { name: 'ABI L2 CTPC (Full)', bands: ABI_BANDS },
        'ABI-L2-DMWC': { name: 'ABI L2 DMW (CONUS)', bands: ABI_BANDS },
        'ABI-L2-DMWF': { name: 'ABI L2 DMW (Full)', bands: ABI_BANDS },
        'ABI-L2-DMWM': { name: 'ABI L2 DMW (Mesoscale)', bands: ABI_BANDS },
        'ABI-L2-DMWVC': { name: 'ABI L2 DMWV (CONUS)', bands: ABI_BANDS },
        'ABI-L2-DMWVF': { name: 'ABI L2 DMWV (Full)', bands: ABI_BANDS },
        'ABI-L2-DMWVM': { name: 'ABI L2 DMWV (Mesoscale)', bands: ABI_BANDS },
        'ABI-L2-DSIC': { name: 'ABI L2 DSIC (CONUS)', bands: ABI_BANDS },
        'ABI-L2-DSIF': { name: 'ABI L2 DSIC (Full)', bands: ABI_BANDS },
        'ABI-L2-DSIM': { name: 'ABI L2 DSIC (Mesoscale)', bands: ABI_BANDS },
        'ABI-L2-DSRC': { name: 'ABI L2 DSRC (CONUS)', bands: ABI_BANDS },
        'ABI-L2-DSRF': { name: 'ABI L2 DSRC (Full)', bands: ABI_BANDS },
        'ABI-L2-DSRM': { name: 'ABI L2 DSRC (Mesoscale)', bands: ABI_BANDS },
        'ABI-L2-FDCC': { name: 'ABI L2 FDCC (CONUS)', bands: ABI_BANDS },
        'ABI-L2-FDCF': { name: 'ABI L2 FDCC (Full)', bands: ABI_BANDS },
        'ABI-L2-FDCM': { name: 'ABI L2 FDCC (Mesoscale)', bands: ABI_BANDS },
        'ABI-L2-FSCC': { name: 'ABI L2 FSCC (CONUS)', bands: ABI_BANDS },
        'ABI-L2-FSCF': { name: 'ABI L2 FSCC (Full)', bands: ABI_BANDS },
        'ABI-L2-FSCM': { name: 'ABI L2 FSCC (Mesoscale)', bands: ABI_BANDS },
        'ABI-L2-LSAC': { name: 'ABI L2 LSAC (CONUS)', bands: ABI_BANDS },
        'ABI-L2-LSAF': { name: 'ABI L2 LSA (Full)', bands: ABI_BANDS },
        'ABI-L2-LSAM': { name: 'ABI L2 LSA (Mesoscale)', bands: ABI_BANDS },
        'ABI-L2-LST2KMF': { name: 'ABI L2 LST2KM (Full)', bands: ABI_BANDS },
        'ABI-L2-LSTC': { name: 'ABI L2 LST (CONUS)', bands: ABI_BANDS },
        'ABI-L2-LSTF': { name: 'ABI L2 LST (Full)', bands: ABI_BANDS },
        'ABI-L2-LSTM': { name: 'ABI L2 LST (Mesoscale)', bands: ABI_BANDS },
        'ABI-L2-LVMPC': { name: 'ABI L2 LVMP (CONUS)', bands: ABI_BANDS },
        'ABI-L2-LVMPF': { name: 'ABI L2 LVMP (Full)', bands: ABI_BANDS },
        'ABI-L2-LVMPM': { name: 'ABI L2 LVMP (Mesoscale)', bands: ABI_BANDS },
        'ABI-L2-LVTPC': { name: 'ABI L2 LVTP (CONUS)', bands: ABI_BANDS },
        'ABI-L2-LVTPF': { name: 'ABI L2 LVTP (Full)', bands: ABI_BANDS },
        'ABI-L2-LVTPM': { name: 'ABI L2 LVTP (Mesoscale)', bands: ABI_BANDS },
        'ABI-L2-MCMIPC': { name: 'ABI L2 MCMIP (CONUS)', bands: ABI_BANDS },
        'ABI-L2-MCMIPF': { name: 'ABI L2 MCMIP (Full)', bands: ABI_BANDS },
        'ABI-L2-MCMIPM': { name: 'ABI L2 MCMIP (Mesoscale)', bands: ABI_BANDS },
        'ABI-L2-PARF': { name: 'ABI L2 PAR (Full)', bands: ABI_BANDS },
        'ABI-L2-RRQPEF': { name: 'ABI L2 RRQPE (Full)', bands: ABI_BANDS },
        'ABI-L2-RSRC': { name: 'ABI L2 RSRC (CONUS)', bands: ABI_BANDS },
        'ABI-L2-RSRF': { name: 'ABI L2 RSR (Full)', bands: ABI_BANDS },
        'ABI-L2-SSTF': { name: 'ABI L2 SST (Full)', bands: ABI_BANDS },
        'ABI-L2-TPWC': { name: 'ABI L2 TPW (CONUS)', bands: ABI_BANDS },
        'ABI-L2-TPWF': { name: 'ABI L2 TPW (Full)', bands: ABI_BANDS },
        'ABI-L2-TPWM': { name: 'ABI L2 TPW (Mesoscale)', bands: ABI_BANDS },
        'EXIS-L1b-SFEU': { name: 'EXIS L1b SFEU', bands: null },
        'EXIS-L1b-SFXR': { name: 'EXIS L1b SFXR', bands: null },
        'GLM-L2-LCFA': { name: 'GLM L2 LCFA', bands: null },
        'MAG-L1b-GEOF': { name: 'MAG L1b GEOF', bands: null },
        'SEIS-L1b-EHIS': { name: 'SEIS L1b EHIS', bands: null },
        'SEIS-L1b-MPSH': { name: 'SEIS L1b MPSH', bands: null },
        'SEIS-L1b-MPSL': { name: 'SEIS L1b MPSL', bands: null },
        'SEIS-L1b-SGPS': { name: 'SEIS L1b SGPS', bands: null },
        'SUVI-L1b-Fe093': { name: 'SUVI L1b Fe093', bands: null },
        'SUVI-L1b-Fe131': { name: 'SUVI L1b Fe131', bands: null },
        'SUVI-L1b-Fe171': { name: 'SUVI L1b Fe171', bands: null },
        'SUVI-L1b-Fe195': { name: 'SUVI L1b Fe195', bands: null },
        'SUVI-L1b-Fe284': { name: 'SUVI L1b Fe284', bands: null },
        'SUVI-L1b-He303': { name: 'SUVI L1b He303', bands: null }
      }
    },
    'Suomi NPP': {
      bucket: 'noaa-snpp',
      products: {
        'VIIRS-L1': { name: 'VIIRS L1', bands: ['I1', 'I2', 'I3', 'I4', 'I5', 'M1', 'M2', 'M3', 'M4', 'M5', 'M6', 'M7', 'M8', 'M9', 'M10', 'M11', 'M12', 'M13', 'M14', 'M15', 'M16'] },
        'VIIRS-L2-ACSPO': { name: 'VIIRS L2 ACSPO Sea Surface', bands: null },
        'VIIRS-L2-CALIOP': { name: 'VIIRS L2 CALIOP', bands: null },
        'VIIRS-L2-CorrectedReflectance': { name: 'VIIRS L2 Corrected Reflectance', bands: null },
        'VIIRS-L2-IAB': { name: 'VIIRS L2 IAB', bands: null },
        'VIIRS-L2-SNCO': { name: 'VIIRS L2 SNCO', bands: null },
        'VIIRS-L2-VNP03MODIS': { name: 'VIIRS L2 Geolocation', bands: null },
        'VIIRS-L3-NDVI': { name: 'VIIRS L3 NDVI', bands: null },
        'VIIRS-L3-NDSI': { name: 'VIIRS L3 NDSI', bands: null },
        'CrIS-L1b-QL': { name: 'CrIS L1b Quality', bands: null },
        'OMPS-L2-SO2': { name: 'OMPS L2 SO2', bands: null },
        'ATMS-L1b': { name: 'ATMS L1b', bands: null }
      }
    },
    'NOAA-20': {
      bucket: 'noaa-j1',
      products: {
        'VIIRS-L1': { name: 'VIIRS L1', bands: ['I1', 'I2', 'I3', 'I4', 'I5', 'M1', 'M2', 'M3', 'M4', 'M5', 'M6', 'M7', 'M8', 'M9', 'M10', 'M11', 'M12', 'M13', 'M14', 'M15', 'M16'] },
        'VIIRS-L2-ACSPO': { name: 'VIIRS L2 ACSPO', bands: null },
        'VIIRS-L2-CorrectedReflectance': { name: 'VIIRS L2 Corrected Reflectance', bands: null },
        'VIIRS-L2-DNB': { name: 'VIIRS L2 Day/Night Band', bands: null },
        'VIIRS-L2-SNCO': { name: 'VIIRS L2 SNCO', bands: null },
        'VIIRS-L3-NDVI': { name: 'VIIRS L3 NDVI', bands: null },
        'CrIS-L1b-QL': { name: 'CrIS L1b Quality', bands: null },
        'ATMS-L1b': { name: 'ATMS L1b', bands: null }
      }
    },
    'NOAA-21': {
      bucket: 'noaa-j2',
      products: {
        'VIIRS-L1': { name: 'VIIRS L1', bands: ['I1', 'I2', 'I3', 'I4', 'I5', 'M1', 'M2', 'M3', 'M4', 'M5', 'M6', 'M7', 'M8', 'M9', 'M10', 'M11', 'M12', 'M13', 'M14', 'M15', 'M16'] },
        'VIIRS-L2-ACSPO': { name: 'VIIRS L2 ACSPO', bands: null },
        'VIIRS-L2-CorrectedReflectance': { name: 'VIIRS L2 Corrected Reflectance', bands: null },
        'VIIRS-L2-DNB': { name: 'VIIRS L2 Day/Night Band', bands: null },
        'VIIRS-L2-SNCO': { name: 'VIIRS L2 SNCO', bands: null },
        'VIIRS-L3-NDVI': { name: 'VIIRS L3 NDVI', bands: null },
        'CrIS-L1b-QL': { name: 'CrIS L1b Quality', bands: null },
        'ATMS-L1b': { name: 'ATMS L1b', bands: null }
      }
    }
  },

  // Band information for GOES
  bandInfo: {
    'C01': { name: 'Blue', wavelength: '0.47 µm' },
    'C02': { name: 'Red', wavelength: '0.64 µm' },
    'C03': { name: 'Vegetation', wavelength: '0.86 µm' },
    'C04': { name: 'Cirrus', wavelength: '1.37 µm' },
    'C05': { name: 'SWIR', wavelength: '1.6 µm' },
    'C06': { name: 'SWIR', wavelength: '2.2 µm' },
    'C07': { name: 'Water Vapor', wavelength: '3.9 µm' },
    'C08': { name: 'Water Vapor', wavelength: '6.2 µm' },
    'C09': { name: 'Water Vapor', wavelength: '6.9 µm' },
    'C10': { name: 'SO2', wavelength: '7.3 µm' },
    'C11': { name: 'Ash', wavelength: '8.4 µm' },
    'C12': { name: 'Ash', wavelength: '9.6 µm' },
    'C13': { name: 'Clean IR', wavelength: '10.3 µm' },
    'C14': { name: 'Longwave IR', wavelength: '11.2 µm' },
    'C15': { name: 'Longwave IR', wavelength: '12.3 µm' },
    'C16': { name: 'CO2', wavelength: '13.3 µm' }
  }
};

if (typeof module !== 'undefined' && module.exports) {
  module.exports = CONFIG;
}
